---
title: "regression-analysis"
author: "Jack Regan"
date: "2024-11-25"
output: pdf_document
---

```{r}
#| label: import-library
library(tidyverse)
library(tidymodels)
options(scipen = 999)
```

```{r}
#| label: import-data
data <- read.csv("data/regression-data.csv")
```

```{r}
#| label: calculate-voter-turnout

data <- data |>
  mutate(
    Voter_Turnout = (Counted_Ballots/Eligible_Population) * 100
  )
```

```{r}
#| label: add-categorical-variable-local-news

data <- data |>
  mutate(
    Local_News_Cat = case_when(
      Local_News_Outlets == 0 ~ "None",
      Local_News_Outlets == 1 ~ "One",
      .default = "More than One"
    ),
    Local_News_Cat = factor(Local_News_Cat, levels = c("None", "One", "More than One"))
  )

data |>
```

```{r}
#| label: median-turnout-comparison

median_turnout <- data |>
  group_by(Local_News_Cat) |>
  summarize(
    Median_Turnout = round(median(Voter_Turnout), digits = 2)
  )
```

```{r}
#| label: visualize-median-turnout

ggplot(median_turnout, aes(x = Local_News_Cat, y = Median_Turnout)) +
  geom_col(fill = "black", width = 0.4) + 
  geom_text(aes(label = paste(Median_Turnout, "%")), vjust = -0.5) +
  theme_minimal() +
  theme(
    text = element_text(color = "black"),
    panel.grid = element_blank(),
    axis.line = element_line(color = "black"),
    axis.title = element_text(face = "bold", family = "Arial", size = 12)
  ) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 100)) +
  labs(
    x = "Number of Local News Outlets",
    y = "Voter Turnout Rate"
  )
```

```{r}
#| label: linear-regression

set.seed(08242932)

data_split <- initial_split(data)
data_train <- training(data_split)
data_test <- testing(data_split)

data_fit <- linear_reg() |>
  fit(Voter_Turnout ~ Local_News_Outlets + HS_Graduation_Rate + Mean_Earnings, data = data_train)

summary(data_fit$fit)

```